name: CMIP6-201910
channels:
- conda-forge
dependencies:
- altair
- basemap
- bokeh=1.3
- bottleneck
- cartopy
- cf_units
- cfgrib
- cftime
- climlab
- climpred
- cmocean
- cython
- dask-jobqueue
- dask-ml
- dask-mpi
- dask>=2.5.2
- datashader
- descartes
- distributed>=2.5
- eofs
- erddapy
- esmlab
- esmpy
- fastparquet
- folium
- fsspec
- geopandas
- geoviews
- graphviz=2.40
- gsw
- h5netcdf
- h5py
- holoviews
- hvplot
- intake
- intake-stac
- intake-xarray
- ipyleaflet
- ipywidgets
- iris
- jupyter-server-proxy=1.1
- jupyter_contrib_nbextensions
- jupyterlab=1
- keras
- line_profiler
- lz4
- matplotlib
- memory_profiler
- metpy
- mpi4py
- nbconvert
- nbdime
- nbgitpuller=0.7
- nc-time-axis
- netcdf4
- nodejs
- numba
- numcodecs
- numpy
- palettable
- pandas
- pandoc
- pandocfilters
- panel
- pint
- pip
- psutil
- psyplot
- pyarrow
- pydap
- pyinterp
- pyresample
- pytest
- python-blosc
- python-graphviz
- python-wget
- pytide
- pytorch-cpu #- pytorch-gpu ??? or a separate environment?
- rasterio
- regionmask
- rio-cogeo
- satpy
- scikit-image
- scikit-learn
- scipy
- seaborn
- seawater
- siphon
- snakeviz
- sparse
- statsmodels
- sympy
- tabulate
- tensorflow
- tiledb-py
- toolz
- tornado=6
- tqdm
- vega
- vega_datasets
- watermark
- windspharm
- wrf-python
- xarray
- xesmf
- xgcm
- xhistogram
- xlrd
- xrft
- zarr
- pip:
  - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
  - graphviz
  - ncar-jobqueue
  - intake-esm
